### ISSUE TITLE
Infografia Ameli Reyes Hernández 4bs 

### ISSUE THREAD

**Issue by AmeliReyesHernandez** [SistemasTecTlaxiaco/infografia-de-hilos-AmeliReyesHernandez#2]
[Inforgrafia Hilos AMELI REYES HERNANDEZ 4BS.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-AmeliReyesHernandez/files/15067537/Inforgrafia.Hilos.AMELI.REYES.HERNANDEZ.4BS.pdf)

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rubrica obtuvo un 19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
